name: env_RAG
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11  # Or 3.10 — depending on your preference
  - pip
  - numpy
  - pandas
  - tqdm
  - pytorch=2.6.0
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - scikit-learn
  - transformers
  - accelerate
  - matplotlib
  - pip:
      - InstructorEmbedding
      - sentence-transformers
      - chromadb
